services:
  mongo:
    image: mongo:latest
    volumes:
      - mongo_data:/data/db
  web:
    build: .
    ports:
      - "5010:5000"
    environment:
      - FLASK_APP=app.py
      - MONGO_URI=mongodb://mongo:27017/examDB
    depends_on:
      - mongo
    command: >
      sh -c "sleep 5; python load_data_to_mongodb.py && flask run --host=0.0.0.0"

volumes:
  mongo_data:
